wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.11
    cli_version: 0.20.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1750166528
    t:
      1:
      - 1
      - 41
      3:
      - 4
      - 13
      - 16
      - 42
      - 55
      4: 3.12.11
      5: 0.20.1
      13: linux-x86_64
learning_rate:
  desc: null
  value: 0.01
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-10
epochs:
  desc: null
  value: 4
Batch_size:
  desc: null
  value: 128
momentum:
  desc: null
  value: 0.9
timesteps:
  desc: null
  value: 5
training_condition:
  desc: null
  value: pc_train
Training The Model:
  desc: null
  value: true
Testing The Model:
  desc: null
  value: false
