wandb_version: 1

batch_size:
  value: 64
datasetpath:
  value: /home/ajinkyar/datasets
device:
  value: cuda:0
epochs:
  value: 10
lr:
  value: 0.0016777034459086188
momentum:
  value: 0.6701360007516388
seed:
  value: 999
timesteps:
  value: 15
training_condition:
  value: pc_train
