wandb_version: 1

batch_size:
  value: 64
datasetpath:
  value: /home/ajinkyar/datasets
device:
  value: cuda:0
epochs:
  value: 10
lr:
  value: 0.09566713083805446
momentum:
  value: 0.961706020252238
seed:
  value: 789
timesteps:
  value: 15
training_condition:
  value: pc_train
