_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
                - 2
                - 13
                - 16
                - 55
            "4": 3.12.11
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
Alpha_layer0:
    value: 0.01
Alpha_layer1:
    value: 0.01
Alpha_layer2:
    value: 0.01
Alpha_layer3:
    value: 0.01
Batch_size:
    value: 128
Beta_layer0:
    value: 0.23
Beta_layer1:
    value: 0.33
Beta_layer2:
    value: 0.33
Beta_layer3:
    value: 0.33
Gamma_layer0:
    value: 0.33
Gamma_layer1:
    value: 0.33
Gamma_layer2:
    value: 0.33
Gamma_layer3:
    value: 0.33
Model_Name:
    value: ff_fb_model
architecture:
    value: CNN
dataset:
    value: CIFAR-10
epochs:
    value: 70
learning_rate:
    value: 0.001
momentum:
    value: 0.9
noise_param:
    value: 0.02
noise_type:
    value: s&p
timesteps:
    value: 10
training_condition:
    value: null
