wandb_version: 1

batch_size:
  value: 32
datasetpath:
  value: /home/ajinkyar/datasets
device:
  value: cuda:0
epochs:
  value: 10
lr:
  value: 0.0067505988578387965
momentum:
  value: 0.7025168038279153
seed:
  value: 123
timesteps:
  value: 5
training_condition:
  value: pc_train
